fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile



bbm_frontend_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BBMFrontendBundle:Default:index }





BBMFrontendBundle_user_getUser:
    pattern:  /user/getuser/{_format}
    defaults: { _controller: BBMFrontendBundle:User:getUser }
    requirements:
      _format: (json|xml)

BBMFrontendBundle_user_updateUserCriterias:
    pattern:  /user/updateusercriterias/{_format}
    defaults: { _controller: BBMFrontendBundle:User:updateUserCriterias }
    requirements:
      _format: (json|xml)





BBMFrontendBundle_notification_addNotification:
    pattern:  /notification/addnotification/{_format}
    defaults: { _controller: BBMFrontendBundle:Notification:addNotification }
    requirements:
      _format: (json|xml)

BBMFrontendBundle_notification_viewNotifications:
    pattern:  /notification/viewnotification/{_format}
    defaults: { _controller: BBMFrontendBundle:Notification:viewNotifications }
    requirements:
      _format: (json|xml)

BBMFrontendBundle_notification_getNotificationsNumber:
    pattern:  /notification/getnotificationnumber/{_format}
    defaults: { _controller: BBMFrontendBundle:Notification:getNotificationsNumber }
    requirements:
      _format: (json|xml)

BBMFrontendBundle_notification_getAllNotifications:
    pattern:  /notification/getallnotifications/{_format}
    defaults: { _controller: BBMFrontendBundle:Notification:getAllNotifications }
    requirements:
      _format: (json|xml)






BBMFrontendBundle_notification_getLangFile:
    pattern:  /lang/getlangfile/{_format}
    defaults: { _controller: BBMFrontendBundle:Lang:getLangFile }
    requirements:
      _format: (json|xml)


