parameters:
#    bbm_frontend.example.class: BBM\Bundle\FrontendBundle\Example

services:
#    bbm_frontend.example:
#        class: %bbm_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
